{
  "Name": "binarization_adaptive.py",
  "Description": "Binaryzacja - threshold gaussian",
  "Parameters": [
    {
      "Name": "type",
      "Description": "Typ binaryzacji",
      "Value": "ADAPTIVE_THRESH_GAUSSIAN_C",
      "PossibleValues": "ADAPTIVE_THRESH_GAUSSIAN_C",
      "ParameterType": 3
    },
    {
      "Name": "maxVal",
      "Description": "maxVal",
      "Value": "0",
      "PossibleValues": "",
      "ParameterType": 0
    }
  ]
}