{
  "Name": "binarization_adaptive.py",
  "Description": "Binaryzacja - threshold mean",
  "Parameters": [
    {
      "Name": "type",
      "Description": "Typ binaryzacji",
      "Value": "ADAPTIVE_THRESH_MEAN_C",
      "PossibleValues": "ADAPTIVE_THRESH_MEAN_C,",
      "ParameterType": 3
    },
    {
      "Name": "maxVal",
      "Description": "maxVal",
      "Value": "0",
      "PossibleValues": "",
      "ParameterType": 0
    }
  ]
}